DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS item_info;
DROP TABLE IF EXISTS actual;
DROP TABLE IF EXISTS records;

CREATE TABLE users(
    id UNSIGNED INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(20),
    phone VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(50) NOT NULL,
    valid BOOLEAN DEFAULT 0 NOT NULL,
    admin BOOLEAN DEFAULT 0 NOT NULL
);

CREATE TABLE item_info(
    id UNSIGNED INT PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE actual(
    id UNSIGNED INT NOT NULL UNIQUE,
    quantity UNSIGNED INT NOT NULL DEFAULT 0,
    FOREIGN KEY (id) REFERENCES item_info(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE records(
    id UNSIGNED INT PRIMARY KEY AUTOINCREMENT,
    operation_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id UNSIGNED INT FOREIGN KEY REFERENCES users(id) ON UPDATE CASCADE ON DELETE SET NULL,
    operation SET("TOOK", "ADDED"),
    item_id UNSIGNED INT FOREIGN KEY REFERENCES item_info(id) ON UPDATE CASCADE ON DELETE SET NULL,
    quantity UNSIGNED INT NOT NULL
);